apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: kube-prometheus-stack
  source:
    path: argocd/manifests/kube-prometheus-stack.yaml
    repoURL: https://github.com/deggja/azure-argo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
